/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: linearfold.i

package linearfold

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
extern void _wrap_Swig_free_linearfold_14e82afb9161ef6b(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_linearfold_14e82afb9161ef6b(swig_intgo arg1);
extern swig_intgo _wrap_MANNER_NONE_linearfold_14e82afb9161ef6b(void);
extern swig_intgo _wrap_MANNER_H_linearfold_14e82afb9161ef6b(void);
extern swig_intgo _wrap_MANNER_HAIRPIN_linearfold_14e82afb9161ef6b(void);
extern swig_intgo _wrap_MANNER_SINGLE_linearfold_14e82afb9161ef6b(void);
extern swig_intgo _wrap_MANNER_HELIX_linearfold_14e82afb9161ef6b(void);
extern swig_intgo _wrap_MANNER_MULTI_linearfold_14e82afb9161ef6b(void);
extern swig_intgo _wrap_MANNER_MULTI_eq_MULTI_plus_U_linearfold_14e82afb9161ef6b(void);
extern swig_intgo _wrap_MANNER_P_eq_MULTI_linearfold_14e82afb9161ef6b(void);
extern swig_intgo _wrap_MANNER_M2_eq_M_plus_P_linearfold_14e82afb9161ef6b(void);
extern swig_intgo _wrap_MANNER_M_eq_M2_linearfold_14e82afb9161ef6b(void);
extern swig_intgo _wrap_MANNER_M_eq_M_plus_U_linearfold_14e82afb9161ef6b(void);
extern swig_intgo _wrap_MANNER_M_eq_P_linearfold_14e82afb9161ef6b(void);
extern swig_intgo _wrap_MANNER_C_eq_C_plus_U_linearfold_14e82afb9161ef6b(void);
extern swig_intgo _wrap_MANNER_C_eq_C_plus_P_linearfold_14e82afb9161ef6b(void);
extern void _wrap_State_score_set_linearfold_14e82afb9161ef6b(uintptr_t arg1, double arg2);
extern double _wrap_State_score_get_linearfold_14e82afb9161ef6b(uintptr_t arg1);
extern void _wrap_State_manner_set_linearfold_14e82afb9161ef6b(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_State_manner_get_linearfold_14e82afb9161ef6b(uintptr_t arg1);
extern void _wrap_State_trace_set_linearfold_14e82afb9161ef6b(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_State_trace_get_linearfold_14e82afb9161ef6b(uintptr_t arg1);
extern uintptr_t _wrap_new_State__SWIG_0_linearfold_14e82afb9161ef6b(void);
extern uintptr_t _wrap_new_State__SWIG_1_linearfold_14e82afb9161ef6b(double arg1, swig_intgo arg2);
extern void _wrap_State_set__SWIG_0_linearfold_14e82afb9161ef6b(uintptr_t arg1, double arg2, swig_intgo arg3);
extern void _wrap_State_set__SWIG_1_linearfold_14e82afb9161ef6b(uintptr_t arg1, double arg2, swig_intgo arg3, swig_intgo arg4);
extern void _wrap_State_set__SWIG_2_linearfold_14e82afb9161ef6b(uintptr_t arg1, double arg2, swig_intgo arg3, char arg4, swig_intgo arg5);
extern void _wrap_delete_State_linearfold_14e82afb9161ef6b(uintptr_t arg1);
extern void _wrap_TraceInfo_split_set_linearfold_14e82afb9161ef6b(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_TraceInfo_split_get_linearfold_14e82afb9161ef6b(uintptr_t arg1);
extern uintptr_t _wrap_new_TraceInfo_linearfold_14e82afb9161ef6b(void);
extern void _wrap_delete_TraceInfo_linearfold_14e82afb9161ef6b(uintptr_t arg1);
extern void _wrap_BeamCKYParser_beam_set_linearfold_14e82afb9161ef6b(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_BeamCKYParser_beam_get_linearfold_14e82afb9161ef6b(uintptr_t arg1);
extern void _wrap_BeamCKYParser_no_sharp_turn_set_linearfold_14e82afb9161ef6b(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_BeamCKYParser_no_sharp_turn_get_linearfold_14e82afb9161ef6b(uintptr_t arg1);
extern void _wrap_BeamCKYParser_is_verbose_set_linearfold_14e82afb9161ef6b(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_BeamCKYParser_is_verbose_get_linearfold_14e82afb9161ef6b(uintptr_t arg1);
extern void _wrap_BeamCKYParser_use_constraints_set_linearfold_14e82afb9161ef6b(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_BeamCKYParser_use_constraints_get_linearfold_14e82afb9161ef6b(uintptr_t arg1);
extern uintptr_t _wrap_new_BeamCKYParser__SWIG_0_linearfold_14e82afb9161ef6b(swig_intgo arg1, _Bool arg2, _Bool arg3, _Bool arg4);
extern uintptr_t _wrap_new_BeamCKYParser__SWIG_1_linearfold_14e82afb9161ef6b(swig_intgo arg1, _Bool arg2, _Bool arg3);
extern uintptr_t _wrap_new_BeamCKYParser__SWIG_2_linearfold_14e82afb9161ef6b(swig_intgo arg1, _Bool arg2);
extern uintptr_t _wrap_new_BeamCKYParser__SWIG_3_linearfold_14e82afb9161ef6b(swig_intgo arg1);
extern uintptr_t _wrap_new_BeamCKYParser__SWIG_4_linearfold_14e82afb9161ef6b(void);
extern uintptr_t _wrap_BeamCKYParser_parse_linearfold_14e82afb9161ef6b(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern void _wrap_delete_BeamCKYParser_linearfold_14e82afb9161ef6b(uintptr_t arg1);
extern void _wrap_DecoderResult_structure_set_linearfold_14e82afb9161ef6b(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_DecoderResult_structure_get_linearfold_14e82afb9161ef6b(uintptr_t arg1);
extern void _wrap_DecoderResult_score_set_linearfold_14e82afb9161ef6b(uintptr_t arg1, double arg2);
extern double _wrap_DecoderResult_score_get_linearfold_14e82afb9161ef6b(uintptr_t arg1);
extern void _wrap_DecoderResult_num_states_set_linearfold_14e82afb9161ef6b(uintptr_t arg1, swig_type_1 arg2);
extern swig_type_2 _wrap_DecoderResult_num_states_get_linearfold_14e82afb9161ef6b(uintptr_t arg1);
extern void _wrap_DecoderResult_time_set_linearfold_14e82afb9161ef6b(uintptr_t arg1, double arg2);
extern double _wrap_DecoderResult_time_get_linearfold_14e82afb9161ef6b(uintptr_t arg1);
extern uintptr_t _wrap_new_DecoderResult_linearfold_14e82afb9161ef6b(void);
extern void _wrap_delete_DecoderResult_linearfold_14e82afb9161ef6b(uintptr_t arg1);
extern void _wrap__allowed_pairs_set_linearfold_14e82afb9161ef6b(swig_voidp arg1);
extern swig_voidp _wrap__allowed_pairs_get_linearfold_14e82afb9161ef6b(void);
extern void _wrap__helix_stacking_set_linearfold_14e82afb9161ef6b(swig_voidp arg1);
extern swig_voidp _wrap__helix_stacking_get_linearfold_14e82afb9161ef6b(void);
extern void _wrap_cache_single_set_linearfold_14e82afb9161ef6b(swig_voidp arg1);
extern swig_voidp _wrap_cache_single_get_linearfold_14e82afb9161ef6b(void);
extern void _wrap_initialize_cachesingle_linearfold_14e82afb9161ef6b(void);
extern void _wrap_initialize_linearfold_14e82afb9161ef6b(void);
extern double _wrap_base_pair_score_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2);
extern double _wrap_helix_stacking_score_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4);
extern double _wrap_helix_closing_score_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2);
extern double _wrap_terminal_mismatch_score_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4);
extern double _wrap_bulge_nuc_score_linearfold_14e82afb9161ef6b(swig_intgo arg1);
extern double _wrap_internal_nuc_score_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2);
extern double _wrap_dangle_left_score_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3);
extern double _wrap_dangle_right_score_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3);
extern double _wrap_hairpin_score_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2);
extern double _wrap_internal_length_score_linearfold_14e82afb9161ef6b(swig_intgo arg1);
extern double _wrap_internal_explicit_score_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2);
extern double _wrap_internal_sym_score_linearfold_14e82afb9161ef6b(swig_intgo arg1);
extern double _wrap_internal_asym_score_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2);
extern double _wrap_bulge_length_score_linearfold_14e82afb9161ef6b(swig_intgo arg1);
extern double _wrap_hairpin_at_least_score_linearfold_14e82afb9161ef6b(swig_intgo arg1);
extern double _wrap_buldge_length_at_least_score_linearfold_14e82afb9161ef6b(swig_intgo arg1);
extern double _wrap_internal_length_at_least_score_linearfold_14e82afb9161ef6b(swig_intgo arg1);
extern double _wrap_score_junction_A_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6, swig_intgo arg7);
extern double _wrap_score_junction_B_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6);
extern double _wrap_score_hairpin_length_linearfold_14e82afb9161ef6b(swig_intgo arg1);
extern double _wrap_score_hairpin_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6);
extern double _wrap_score_helix_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4);
extern double _wrap_score_single_nuc_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6);
extern double _wrap_score_single_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6, swig_intgo arg7, swig_intgo arg8, swig_intgo arg9, swig_intgo arg10, swig_intgo arg11, swig_intgo arg12, swig_intgo arg13);
extern double _wrap_score_single_without_junctionB_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6, swig_intgo arg7, swig_intgo arg8);
extern double _wrap_score_multi_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6, swig_intgo arg7);
extern double _wrap_score_multi_unpaired_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2);
extern double _wrap_score_M1_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6, swig_intgo arg7, swig_intgo arg8);
extern double _wrap_score_external_paired_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6, swig_intgo arg7);
extern double _wrap_score_external_unpaired_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_MIN2_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_MAX2_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2);
extern void _wrap_v_init_tetra_hex_tri_linearfold_14e82afb9161ef6b(uintptr_t arg1, swig_intgo arg2, uintptr_t arg3, uintptr_t arg4, uintptr_t arg5);
extern swig_intgo _wrap_v_score_hairpin__SWIG_0_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6, swig_intgo arg7);
extern swig_intgo _wrap_v_score_hairpin__SWIG_1_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6);
extern swig_intgo _wrap_v_score_single_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6, swig_intgo arg7, swig_intgo arg8, swig_intgo arg9, swig_intgo arg10, swig_intgo arg11, swig_intgo arg12);
extern swig_intgo _wrap_E_MLstem_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3);
extern swig_intgo _wrap_v_score_M1_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6, swig_intgo arg7, swig_intgo arg8);
extern swig_intgo _wrap_v_score_multi_unpaired_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_v_score_multi_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6, swig_intgo arg7);
extern swig_intgo _wrap_v_score_external_paired_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6, swig_intgo arg7);
extern swig_intgo _wrap_v_score_external_unpaired_linearfold_14e82afb9161ef6b(swig_intgo arg1, swig_intgo arg2);
extern swig_type_3 _wrap_eval_linearfold_14e82afb9161ef6b(uintptr_t arg1, uintptr_t arg2, _Bool arg3);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

const MIN_CUBE_PRUNING_SIZE int = 20
type Manner int
func _swig_getMANNER_NONE() (_swig_ret Manner) {
	var swig_r Manner
	swig_r = (Manner)(C._wrap_MANNER_NONE_linearfold_14e82afb9161ef6b())
	return swig_r
}

var MANNER_NONE Manner = _swig_getMANNER_NONE()
func _swig_getMANNER_H() (_swig_ret Manner) {
	var swig_r Manner
	swig_r = (Manner)(C._wrap_MANNER_H_linearfold_14e82afb9161ef6b())
	return swig_r
}

var MANNER_H Manner = _swig_getMANNER_H()
func _swig_getMANNER_HAIRPIN() (_swig_ret Manner) {
	var swig_r Manner
	swig_r = (Manner)(C._wrap_MANNER_HAIRPIN_linearfold_14e82afb9161ef6b())
	return swig_r
}

var MANNER_HAIRPIN Manner = _swig_getMANNER_HAIRPIN()
func _swig_getMANNER_SINGLE() (_swig_ret Manner) {
	var swig_r Manner
	swig_r = (Manner)(C._wrap_MANNER_SINGLE_linearfold_14e82afb9161ef6b())
	return swig_r
}

var MANNER_SINGLE Manner = _swig_getMANNER_SINGLE()
func _swig_getMANNER_HELIX() (_swig_ret Manner) {
	var swig_r Manner
	swig_r = (Manner)(C._wrap_MANNER_HELIX_linearfold_14e82afb9161ef6b())
	return swig_r
}

var MANNER_HELIX Manner = _swig_getMANNER_HELIX()
func _swig_getMANNER_MULTI() (_swig_ret Manner) {
	var swig_r Manner
	swig_r = (Manner)(C._wrap_MANNER_MULTI_linearfold_14e82afb9161ef6b())
	return swig_r
}

var MANNER_MULTI Manner = _swig_getMANNER_MULTI()
func _swig_getMANNER_MULTI_eq_MULTI_plus_U() (_swig_ret Manner) {
	var swig_r Manner
	swig_r = (Manner)(C._wrap_MANNER_MULTI_eq_MULTI_plus_U_linearfold_14e82afb9161ef6b())
	return swig_r
}

var MANNER_MULTI_eq_MULTI_plus_U Manner = _swig_getMANNER_MULTI_eq_MULTI_plus_U()
func _swig_getMANNER_P_eq_MULTI() (_swig_ret Manner) {
	var swig_r Manner
	swig_r = (Manner)(C._wrap_MANNER_P_eq_MULTI_linearfold_14e82afb9161ef6b())
	return swig_r
}

var MANNER_P_eq_MULTI Manner = _swig_getMANNER_P_eq_MULTI()
func _swig_getMANNER_M2_eq_M_plus_P() (_swig_ret Manner) {
	var swig_r Manner
	swig_r = (Manner)(C._wrap_MANNER_M2_eq_M_plus_P_linearfold_14e82afb9161ef6b())
	return swig_r
}

var MANNER_M2_eq_M_plus_P Manner = _swig_getMANNER_M2_eq_M_plus_P()
func _swig_getMANNER_M_eq_M2() (_swig_ret Manner) {
	var swig_r Manner
	swig_r = (Manner)(C._wrap_MANNER_M_eq_M2_linearfold_14e82afb9161ef6b())
	return swig_r
}

var MANNER_M_eq_M2 Manner = _swig_getMANNER_M_eq_M2()
func _swig_getMANNER_M_eq_M_plus_U() (_swig_ret Manner) {
	var swig_r Manner
	swig_r = (Manner)(C._wrap_MANNER_M_eq_M_plus_U_linearfold_14e82afb9161ef6b())
	return swig_r
}

var MANNER_M_eq_M_plus_U Manner = _swig_getMANNER_M_eq_M_plus_U()
func _swig_getMANNER_M_eq_P() (_swig_ret Manner) {
	var swig_r Manner
	swig_r = (Manner)(C._wrap_MANNER_M_eq_P_linearfold_14e82afb9161ef6b())
	return swig_r
}

var MANNER_M_eq_P Manner = _swig_getMANNER_M_eq_P()
func _swig_getMANNER_C_eq_C_plus_U() (_swig_ret Manner) {
	var swig_r Manner
	swig_r = (Manner)(C._wrap_MANNER_C_eq_C_plus_U_linearfold_14e82afb9161ef6b())
	return swig_r
}

var MANNER_C_eq_C_plus_U Manner = _swig_getMANNER_C_eq_C_plus_U()
func _swig_getMANNER_C_eq_C_plus_P() (_swig_ret Manner) {
	var swig_r Manner
	swig_r = (Manner)(C._wrap_MANNER_C_eq_C_plus_P_linearfold_14e82afb9161ef6b())
	return swig_r
}

var MANNER_C_eq_C_plus_P Manner = _swig_getMANNER_C_eq_C_plus_P()
type SwigcptrState uintptr

func (p SwigcptrState) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrState) SwigIsState() {
}

func (arg1 SwigcptrState) SetScore(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_State_score_set_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrState) GetScore() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_State_score_get_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrState) SetManner(arg2 Manner) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_State_manner_set_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrState) GetManner() (_swig_ret Manner) {
	var swig_r Manner
	_swig_i_0 := arg1
	swig_r = (Manner)(C._wrap_State_manner_get_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrState) SetTrace(arg2 TraceInfo) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_State_trace_set_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrState) GetTrace() (_swig_ret TraceInfo) {
	var swig_r TraceInfo
	_swig_i_0 := arg1
	swig_r = (TraceInfo)(SwigcptrTraceInfo(C._wrap_State_trace_get_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewState__SWIG_0() (_swig_ret State) {
	var swig_r State
	swig_r = (State)(SwigcptrState(C._wrap_new_State__SWIG_0_linearfold_14e82afb9161ef6b()))
	return swig_r
}

func NewState__SWIG_1(arg1 float64, arg2 Manner) (_swig_ret State) {
	var swig_r State
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (State)(SwigcptrState(C._wrap_new_State__SWIG_1_linearfold_14e82afb9161ef6b(C.double(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func NewState(a ...interface{}) State {
	argc := len(a)
	if argc == 0 {
		return NewState__SWIG_0()
	}
	if argc == 2 {
		return NewState__SWIG_1(a[0].(float64), a[1].(Manner))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrState) Set__SWIG_0(arg2 float64, arg3 Manner) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_State_set__SWIG_0_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.swig_intgo(_swig_i_2))
}

func (arg1 SwigcptrState) Set__SWIG_1(arg2 float64, arg3 Manner, arg4 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_State_set__SWIG_1_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3))
}

func (arg1 SwigcptrState) Set__SWIG_2(arg2 float64, arg3 Manner, arg4 byte, arg5 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	C._wrap_State_set__SWIG_2_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.swig_intgo(_swig_i_2), C.char(_swig_i_3), C.swig_intgo(_swig_i_4))
}

func (p SwigcptrState) Set(a ...interface{}) {
	argc := len(a)
	if argc == 2 {
		p.Set__SWIG_0(a[0].(float64), a[1].(Manner))
		return
	}
	if argc == 3 {
		p.Set__SWIG_1(a[0].(float64), a[1].(Manner), a[2].(int))
		return
	}
	if argc == 4 {
		p.Set__SWIG_2(a[0].(float64), a[1].(Manner), a[2].(byte), a[3].(int))
		return
	}
	panic("No match for overloaded function call")
}

func DeleteState(arg1 State) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_State_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0))
}

type State interface {
	Swigcptr() uintptr
	SwigIsState()
	SetScore(arg2 float64)
	GetScore() (_swig_ret float64)
	SetManner(arg2 Manner)
	GetManner() (_swig_ret Manner)
	SetTrace(arg2 TraceInfo)
	GetTrace() (_swig_ret TraceInfo)
	Set(a ...interface{})
}

type SwigcptrTraceInfo uintptr

func (p SwigcptrTraceInfo) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrTraceInfo) SwigIsTraceInfo() {
}

func (arg1 SwigcptrTraceInfo) SetSplit(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_TraceInfo_split_set_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrTraceInfo) GetSplit() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_TraceInfo_split_get_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewTraceInfo() (_swig_ret TraceInfo) {
	var swig_r TraceInfo
	swig_r = (TraceInfo)(SwigcptrTraceInfo(C._wrap_new_TraceInfo_linearfold_14e82afb9161ef6b()))
	return swig_r
}

func DeleteTraceInfo(arg1 TraceInfo) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_TraceInfo_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0))
}

type TraceInfo interface {
	Swigcptr() uintptr
	SwigIsTraceInfo()
	SetSplit(arg2 int)
	GetSplit() (_swig_ret int)
}

type SwigcptrBeamCKYParser uintptr

func (p SwigcptrBeamCKYParser) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrBeamCKYParser) SwigIsBeamCKYParser() {
}

func (arg1 SwigcptrBeamCKYParser) SetBeam(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_BeamCKYParser_beam_set_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrBeamCKYParser) GetBeam() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_BeamCKYParser_beam_get_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrBeamCKYParser) SetNo_sharp_turn(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_BeamCKYParser_no_sharp_turn_set_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrBeamCKYParser) GetNo_sharp_turn() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_BeamCKYParser_no_sharp_turn_get_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrBeamCKYParser) SetIs_verbose(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_BeamCKYParser_is_verbose_set_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrBeamCKYParser) GetIs_verbose() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_BeamCKYParser_is_verbose_get_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrBeamCKYParser) SetUse_constraints(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_BeamCKYParser_use_constraints_set_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrBeamCKYParser) GetUse_constraints() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_BeamCKYParser_use_constraints_get_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewBeamCKYParser__SWIG_0(arg1 int, arg2 bool, arg3 bool, arg4 bool) (_swig_ret BeamCKYParser) {
	var swig_r BeamCKYParser
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (BeamCKYParser)(SwigcptrBeamCKYParser(C._wrap_new_BeamCKYParser__SWIG_0_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C._Bool(_swig_i_1), C._Bool(_swig_i_2), C._Bool(_swig_i_3))))
	return swig_r
}

func NewBeamCKYParser__SWIG_1(arg1 int, arg2 bool, arg3 bool) (_swig_ret BeamCKYParser) {
	var swig_r BeamCKYParser
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (BeamCKYParser)(SwigcptrBeamCKYParser(C._wrap_new_BeamCKYParser__SWIG_1_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C._Bool(_swig_i_1), C._Bool(_swig_i_2))))
	return swig_r
}

func NewBeamCKYParser__SWIG_2(arg1 int, arg2 bool) (_swig_ret BeamCKYParser) {
	var swig_r BeamCKYParser
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (BeamCKYParser)(SwigcptrBeamCKYParser(C._wrap_new_BeamCKYParser__SWIG_2_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C._Bool(_swig_i_1))))
	return swig_r
}

func NewBeamCKYParser__SWIG_3(arg1 int) (_swig_ret BeamCKYParser) {
	var swig_r BeamCKYParser
	_swig_i_0 := arg1
	swig_r = (BeamCKYParser)(SwigcptrBeamCKYParser(C._wrap_new_BeamCKYParser__SWIG_3_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0))))
	return swig_r
}

func NewBeamCKYParser__SWIG_4() (_swig_ret BeamCKYParser) {
	var swig_r BeamCKYParser
	swig_r = (BeamCKYParser)(SwigcptrBeamCKYParser(C._wrap_new_BeamCKYParser__SWIG_4_linearfold_14e82afb9161ef6b()))
	return swig_r
}

func NewBeamCKYParser(a ...interface{}) BeamCKYParser {
	argc := len(a)
	if argc == 0 {
		return NewBeamCKYParser__SWIG_4()
	}
	if argc == 1 {
		return NewBeamCKYParser__SWIG_3(a[0].(int))
	}
	if argc == 2 {
		return NewBeamCKYParser__SWIG_2(a[0].(int), a[1].(bool))
	}
	if argc == 3 {
		return NewBeamCKYParser__SWIG_1(a[0].(int), a[1].(bool), a[2].(bool))
	}
	if argc == 4 {
		return NewBeamCKYParser__SWIG_0(a[0].(int), a[1].(bool), a[2].(bool), a[3].(bool))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrBeamCKYParser) Parse(arg2 Std_string, arg3 Std_vector_Sl_int_Sg_) (_swig_ret DecoderResult) {
	var swig_r DecoderResult
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (DecoderResult)(SwigcptrDecoderResult(C._wrap_BeamCKYParser_parse_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))))
	return swig_r
}

func DeleteBeamCKYParser(arg1 BeamCKYParser) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_BeamCKYParser_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0))
}

type BeamCKYParser interface {
	Swigcptr() uintptr
	SwigIsBeamCKYParser()
	SetBeam(arg2 int)
	GetBeam() (_swig_ret int)
	SetNo_sharp_turn(arg2 bool)
	GetNo_sharp_turn() (_swig_ret bool)
	SetIs_verbose(arg2 bool)
	GetIs_verbose() (_swig_ret bool)
	SetUse_constraints(arg2 bool)
	GetUse_constraints() (_swig_ret bool)
	Parse(arg2 Std_string, arg3 Std_vector_Sl_int_Sg_) (_swig_ret DecoderResult)
}

type SwigcptrDecoderResult uintptr

func (p SwigcptrDecoderResult) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrDecoderResult) SwigIsDecoderResult() {
}

func (arg1 SwigcptrDecoderResult) SetStructure(arg2 Std_string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_DecoderResult_structure_set_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrDecoderResult) GetStructure() (_swig_ret Std_string) {
	var swig_r Std_string
	_swig_i_0 := arg1
	swig_r = (Std_string)(SwigcptrStd_string(C._wrap_DecoderResult_structure_get_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrDecoderResult) SetScore(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DecoderResult_score_set_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrDecoderResult) GetScore() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_DecoderResult_score_get_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrDecoderResult) SetNum_states(arg2 uint64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DecoderResult_num_states_set_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0), C.swig_type_1(_swig_i_1))
}

func (arg1 SwigcptrDecoderResult) GetNum_states() (_swig_ret uint64) {
	var swig_r uint64
	_swig_i_0 := arg1
	swig_r = (uint64)(C._wrap_DecoderResult_num_states_get_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrDecoderResult) SetTime(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DecoderResult_time_set_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrDecoderResult) GetTime() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_DecoderResult_time_get_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewDecoderResult() (_swig_ret DecoderResult) {
	var swig_r DecoderResult
	swig_r = (DecoderResult)(SwigcptrDecoderResult(C._wrap_new_DecoderResult_linearfold_14e82afb9161ef6b()))
	return swig_r
}

func DeleteDecoderResult(arg1 DecoderResult) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_DecoderResult_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0))
}

type DecoderResult interface {
	Swigcptr() uintptr
	SwigIsDecoderResult()
	SetStructure(arg2 Std_string)
	GetStructure() (_swig_ret Std_string)
	SetScore(arg2 float64)
	GetScore() (_swig_ret float64)
	SetNum_states(arg2 uint64)
	GetNum_states() (_swig_ret uint64)
	SetTime(arg2 float64)
	GetTime() (_swig_ret float64)
}

const INF int = 1000000007
const NOTON int = 5
const NOTOND int = 25
const NOTONT int = 125
const EXPLICIT_MAX_LEN int = 4
const SINGLE_MIN_LEN int = 0
const SINGLE_MAX_LEN int = 30
const HAIRPIN_MAX_LEN int = 30
const BULGE_MAX_LEN int = 30
const INTERNAL_MAX_LEN int = 30
const SYMMETRIC_MAX_LEN int = 15
const ASYMMETRY_MAX_LEN int = 28
func SetX_allowed_pairs(arg1 **bool) {
	_swig_i_0 := arg1
	C._wrap__allowed_pairs_set_linearfold_14e82afb9161ef6b(C.swig_voidp(_swig_i_0))
}

func GetX_allowed_pairs() (_swig_ret **bool) {
	var swig_r **bool
	swig_r = (**bool)(C._wrap__allowed_pairs_get_linearfold_14e82afb9161ef6b())
	return swig_r
}

func SetX_helix_stacking(arg1 ****bool) {
	_swig_i_0 := arg1
	C._wrap__helix_stacking_set_linearfold_14e82afb9161ef6b(C.swig_voidp(_swig_i_0))
}

func GetX_helix_stacking() (_swig_ret ****bool) {
	var swig_r ****bool
	swig_r = (****bool)(C._wrap__helix_stacking_get_linearfold_14e82afb9161ef6b())
	return swig_r
}

func SetCache_single(arg1 **float64) {
	_swig_i_0 := arg1
	C._wrap_cache_single_set_linearfold_14e82afb9161ef6b(C.swig_voidp(_swig_i_0))
}

func GetCache_single() (_swig_ret **float64) {
	var swig_r **float64
	swig_r = (**float64)(C._wrap_cache_single_get_linearfold_14e82afb9161ef6b())
	return swig_r
}

func Initialize_cachesingle() {
	C._wrap_initialize_cachesingle_linearfold_14e82afb9161ef6b()
}

func Initialize() {
	C._wrap_initialize_linearfold_14e82afb9161ef6b()
}

func Base_pair_score(arg1 int, arg2 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float64)(C._wrap_base_pair_score_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Helix_stacking_score(arg1 int, arg2 int, arg3 int, arg4 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (float64)(C._wrap_helix_stacking_score_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3)))
	return swig_r
}

func Helix_closing_score(arg1 int, arg2 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float64)(C._wrap_helix_closing_score_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Terminal_mismatch_score(arg1 int, arg2 int, arg3 int, arg4 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (float64)(C._wrap_terminal_mismatch_score_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3)))
	return swig_r
}

func Bulge_nuc_score(arg1 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_bulge_nuc_score_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Internal_nuc_score(arg1 int, arg2 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float64)(C._wrap_internal_nuc_score_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Dangle_left_score(arg1 int, arg2 int, arg3 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (float64)(C._wrap_dangle_left_score_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func Dangle_right_score(arg1 int, arg2 int, arg3 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (float64)(C._wrap_dangle_right_score_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func Hairpin_score(arg1 int, arg2 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float64)(C._wrap_hairpin_score_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Internal_length_score(arg1 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_internal_length_score_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Internal_explicit_score(arg1 int, arg2 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float64)(C._wrap_internal_explicit_score_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Internal_sym_score(arg1 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_internal_sym_score_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Internal_asym_score(arg1 int, arg2 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float64)(C._wrap_internal_asym_score_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Bulge_length_score(arg1 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_bulge_length_score_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Hairpin_at_least_score(arg1 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_hairpin_at_least_score_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Buldge_length_at_least_score(arg1 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_buldge_length_at_least_score_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Internal_length_at_least_score(arg1 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_internal_length_at_least_score_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Score_junction_A(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int, arg7 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	swig_r = (float64)(C._wrap_score_junction_A_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5), C.swig_intgo(_swig_i_6)))
	return swig_r
}

func Score_junction_B(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (float64)(C._wrap_score_junction_B_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5)))
	return swig_r
}

func Score_hairpin_length(arg1 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_score_hairpin_length_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Score_hairpin(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (float64)(C._wrap_score_hairpin_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5)))
	return swig_r
}

func Score_helix(arg1 int, arg2 int, arg3 int, arg4 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (float64)(C._wrap_score_helix_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3)))
	return swig_r
}

func Score_single_nuc(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (float64)(C._wrap_score_single_nuc_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5)))
	return swig_r
}

func Score_single(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int, arg7 int, arg8 int, arg9 int, arg10 int, arg11 int, arg12 int, arg13 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	_swig_i_9 := arg10
	_swig_i_10 := arg11
	_swig_i_11 := arg12
	_swig_i_12 := arg13
	swig_r = (float64)(C._wrap_score_single_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5), C.swig_intgo(_swig_i_6), C.swig_intgo(_swig_i_7), C.swig_intgo(_swig_i_8), C.swig_intgo(_swig_i_9), C.swig_intgo(_swig_i_10), C.swig_intgo(_swig_i_11), C.swig_intgo(_swig_i_12)))
	return swig_r
}

func Score_single_without_junctionB(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int, arg7 int, arg8 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	swig_r = (float64)(C._wrap_score_single_without_junctionB_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5), C.swig_intgo(_swig_i_6), C.swig_intgo(_swig_i_7)))
	return swig_r
}

func Score_multi(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int, arg7 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	swig_r = (float64)(C._wrap_score_multi_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5), C.swig_intgo(_swig_i_6)))
	return swig_r
}

func Score_multi_unpaired(arg1 int, arg2 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float64)(C._wrap_score_multi_unpaired_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Score_M1(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int, arg7 int, arg8 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	swig_r = (float64)(C._wrap_score_M1_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5), C.swig_intgo(_swig_i_6), C.swig_intgo(_swig_i_7)))
	return swig_r
}

func Score_external_paired(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int, arg7 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	swig_r = (float64)(C._wrap_score_external_paired_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5), C.swig_intgo(_swig_i_6)))
	return swig_r
}

func Score_external_unpaired(arg1 int, arg2 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float64)(C._wrap_score_external_unpaired_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

const MAXLOOP int = 30
func MIN2(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_MIN2_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func MAX2(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_MAX2_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func V_init_tetra_hex_tri(arg1 Std_string, arg2 int, arg3 Std_vector_Sl_int_Sg_, arg4 Std_vector_Sl_int_Sg_, arg5 Std_vector_Sl_int_Sg_) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	_swig_i_4 := arg5.Swigcptr()
	C._wrap_v_init_tetra_hex_tri_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3), C.uintptr_t(_swig_i_4))
}

func V_score_hairpin__SWIG_0(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int, arg7 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	swig_r = (int)(C._wrap_v_score_hairpin__SWIG_0_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5), C.swig_intgo(_swig_i_6)))
	return swig_r
}

func V_score_hairpin__SWIG_1(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (int)(C._wrap_v_score_hairpin__SWIG_1_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5)))
	return swig_r
}

func V_score_hairpin(a ...interface{}) int {
	argc := len(a)
	if argc == 6 {
		return V_score_hairpin__SWIG_1(a[0].(int), a[1].(int), a[2].(int), a[3].(int), a[4].(int), a[5].(int))
	}
	if argc == 7 {
		return V_score_hairpin__SWIG_0(a[0].(int), a[1].(int), a[2].(int), a[3].(int), a[4].(int), a[5].(int), a[6].(int))
	}
	panic("No match for overloaded function call")
}

func V_score_single(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int, arg7 int, arg8 int, arg9 int, arg10 int, arg11 int, arg12 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	_swig_i_9 := arg10
	_swig_i_10 := arg11
	_swig_i_11 := arg12
	swig_r = (int)(C._wrap_v_score_single_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5), C.swig_intgo(_swig_i_6), C.swig_intgo(_swig_i_7), C.swig_intgo(_swig_i_8), C.swig_intgo(_swig_i_9), C.swig_intgo(_swig_i_10), C.swig_intgo(_swig_i_11)))
	return swig_r
}

func E_MLstem(arg1 int, arg2 int, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_E_MLstem_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func V_score_M1(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int, arg7 int, arg8 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	swig_r = (int)(C._wrap_v_score_M1_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5), C.swig_intgo(_swig_i_6), C.swig_intgo(_swig_i_7)))
	return swig_r
}

func V_score_multi_unpaired(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_v_score_multi_unpaired_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func V_score_multi(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int, arg7 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	swig_r = (int)(C._wrap_v_score_multi_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5), C.swig_intgo(_swig_i_6)))
	return swig_r
}

func V_score_external_paired(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int, arg7 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	swig_r = (int)(C._wrap_v_score_external_paired_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5), C.swig_intgo(_swig_i_6)))
	return swig_r
}

func V_score_external_unpaired(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_v_score_external_unpaired_linearfold_14e82afb9161ef6b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Eval(arg1 String, arg2 String, arg3 bool) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	swig_r = (int64)(C._wrap_eval_linearfold_14e82afb9161ef6b(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C._Bool(_swig_i_2)))
	return swig_r
}


type SwigcptrStd_vector_Sl_int_Sg_ uintptr
type Std_vector_Sl_int_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_int_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_string uintptr
type Std_string interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_string) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrString uintptr
type String interface {
	Swigcptr() uintptr;
}
func (p SwigcptrString) Swigcptr() uintptr {
	return uintptr(p)
}

